import type { Metadata } from "next";
import { LearnHeader } from "@/components/learn/learnHeader";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LearnLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <LearnHeader />
      {children}
    </section>
  );
}
